### PR TITLE
Implement spectating

### PR DESCRIPTION
**Pull request by ascenttree**
This pull request aims to add spectating to hexagon

Packets handled:
- [x] Start spectating
- [x] Stop spectating
- [x] Spectator beatmap change
- [x] Spectator frames
- [ ] Has map

### CODE REVIEW

**Review by Lekuruu — COMMENTED** [review]
Looking good! Do you think we could get the "HasBeatmap" packet to work in this PR?

**Comment by ascenttree** [comment]
I don't know exactly how the packet works from server->client, but I know that client sends a u32 (always 1?) followed by a boolean of whether the client has the map or not (both packet id 16)

**Comment by Lekuruu** [comment]
Let's go gambling then

**Review by Lekuruu — APPROVED** [review]
Let's just merge it then, if we can't figure it out right now.

**Pull request merged**
